functional:
  - Необходимо наличие разных режимов игры
  - Необходима реализация разных уровней сложностей
  - В игре должно быть предусмотрено несколько вариаций игровых заданий
  - Должен быть предусмотрен публичная доска лидеров и рейтинги
  - У пользователя должны быть возможность вызвать на "дуэль" любого зарегистрированного игрока
  - Пользователь должен иметь возможность играть против бота
  - Система должна поддерживать разные языки программирования для игры
  - Должен быть реализован личная страница игрока со статистикой и достижениями
non-functional:
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть интуитивно понятным
  - Сайт должен быть удобным на мобильном устройстве
  - Регистрация как самостоятельная, так и через GitHub
  - На сайте реализована система уведомлений
  - Система должна быть надежной
  - Сайт должен маштабироваться с учетом роста количества пользователей
  - В системе пользователю должны быть доступны настройки
  - Сайт при первом запуске должен предложить короткое обучение по возможностям
implicit:
  - Каждый объект или сущность сайта должен иметь возможность быть отредактированным
  - На сайте должна быть реализована система разграничения прав
  - Сайт должен соблюдать законодательство стран, на территории которых работает
